using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("DotNetMarche.Utils for Microsoft .NET Framework 3.5")]
[assembly: AssemblyDescriptionAttribute("DotNetMarche.Utils - Various utilities for every other project of the suite")]
[assembly: AssemblyCompanyAttribute("DotNetMarche")]
[assembly: AssemblyProductAttribute("DotNetMarche.Utils")]
[assembly: AssemblyCopyrightAttribute("Dotnetmarche (c) 2009")]
[assembly: AssemblyVersionAttribute("1.0.2.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.2.75")]
[assembly: AssemblyFileVersionAttribute("1.0.2.75")]
[assembly: AssemblyDelaySignAttribute(false)]

