//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PhotoAlbumModel", "FK_Photo_PhotoAlbum", "PhotoAlbum", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DotNetMarche.PhotoAlbum.Model.PhotoAlbum), "Photo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DotNetMarche.PhotoAlbum.Model.Photo))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PhotoAlbumModel", "FK_PhotoComment_Photo", "Photo", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DotNetMarche.PhotoAlbum.Model.Photo), "PhotoComment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DotNetMarche.PhotoAlbum.Model.PhotoComment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("PhotoAlbumModel", "FK_PhotoComment_Users", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DotNetMarche.PhotoAlbum.Model.Users), "PhotoComment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DotNetMarche.PhotoAlbum.Model.PhotoComment))]

// Original file name:
// Generation date: 2/25/2009 8:24:19 PM
namespace DotNetMarche.PhotoAlbum.Model
{
    
    /// <summary>
    /// There are no comments for PhotoAlbumEntities in the schema.
    /// </summary>
    public partial class PhotoAlbumEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PhotoAlbumEntities object using the connection string found in the 'PhotoAlbumEntities' section of the application configuration file.
        /// </summary>
        public PhotoAlbumEntities() : 
                base("name=PhotoAlbumEntities", "PhotoAlbumEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PhotoAlbumEntities object.
        /// </summary>
        public PhotoAlbumEntities(string connectionString) : 
                base(connectionString, "PhotoAlbumEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new PhotoAlbumEntities object.
        /// </summary>
        public PhotoAlbumEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PhotoAlbumEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Photo> Photo
        {
            get
            {
                if ((this._Photo == null))
                {
                    this._Photo = base.CreateQuery<Photo>("[Photo]");
                }
                return this._Photo;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Photo> _Photo;
        /// <summary>
        /// There are no comments for PhotoAlbum in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PhotoAlbum> PhotoAlbum
        {
            get
            {
                if ((this._PhotoAlbum == null))
                {
                    this._PhotoAlbum = base.CreateQuery<PhotoAlbum>("[PhotoAlbum]");
                }
                return this._PhotoAlbum;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PhotoAlbum> _PhotoAlbum;
        /// <summary>
        /// There are no comments for PhotoComment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PhotoComment> PhotoComment
        {
            get
            {
                if ((this._PhotoComment == null))
                {
                    this._PhotoComment = base.CreateQuery<PhotoComment>("[PhotoComment]");
                }
                return this._PhotoComment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PhotoComment> _PhotoComment;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("[sysdiagrams]");
                }
                return this._sysdiagrams;
            }
        }
        private global::System.Data.Objects.ObjectQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        public void AddToPhoto(Photo photo)
        {
            base.AddObject("Photo", photo);
        }
        /// <summary>
        /// There are no comments for PhotoAlbum in the schema.
        /// </summary>
        public void AddToPhotoAlbum(PhotoAlbum photoAlbum)
        {
            base.AddObject("PhotoAlbum", photoAlbum);
        }
        /// <summary>
        /// There are no comments for PhotoComment in the schema.
        /// </summary>
        public void AddToPhotoComment(PhotoComment photoComment)
        {
            base.AddObject("PhotoComment", photoComment);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    }
    /// <summary>
    /// There are no comments for PhotoAlbumModel.Photo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PhotoAlbumModel", Name="Photo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Photo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="fileName">Initial value of FileName.</param>
        /// <param name="originalFileName">Initial value of OriginalFileName.</param>
        /// <param name="uploadDate">Initial value of UploadDate.</param>
        public static Photo CreatePhoto(global::System.Guid id, string fileName, string originalFileName, global::System.DateTime uploadDate)
        {
            Photo photo = new Photo();
            photo.Id = id;
            photo.FileName = fileName;
            photo.OriginalFileName = originalFileName;
            photo.UploadDate = uploadDate;
            return photo;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for Property OriginalFileName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFileName
        {
            get
            {
                return this._OriginalFileName;
            }
            set
            {
                this.OnOriginalFileNameChanging(value);
                this.ReportPropertyChanging("OriginalFileName");
                this._OriginalFileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("OriginalFileName");
                this.OnOriginalFileNameChanged();
            }
        }
        private string _OriginalFileName;
        partial void OnOriginalFileNameChanging(string value);
        partial void OnOriginalFileNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property UploadDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime UploadDate
        {
            get
            {
                return this._UploadDate;
            }
            set
            {
                this.OnUploadDateChanging(value);
                this.ReportPropertyChanging("UploadDate");
                this._UploadDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UploadDate");
                this.OnUploadDateChanged();
            }
        }
        private global::System.DateTime _UploadDate;
        partial void OnUploadDateChanging(global::System.DateTime value);
        partial void OnUploadDateChanged();
        /// <summary>
        /// There are no comments for PhotoAlbum in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_Photo_PhotoAlbum", "PhotoAlbum")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PhotoAlbum PhotoAlbum
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PhotoAlbum>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "PhotoAlbum").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PhotoAlbum>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "PhotoAlbum").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PhotoAlbum in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PhotoAlbum> PhotoAlbumReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PhotoAlbum>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "PhotoAlbum");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PhotoAlbum>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "PhotoAlbum", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PhotoComment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_PhotoComment_Photo", "PhotoComment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PhotoComment> PhotoComment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PhotoComment>("PhotoAlbumModel.FK_PhotoComment_Photo", "PhotoComment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PhotoComment>("PhotoAlbumModel.FK_PhotoComment_Photo", "PhotoComment", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PhotoAlbumModel.PhotoAlbum in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PhotoAlbumModel", Name="PhotoAlbum")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PhotoAlbum : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PhotoAlbum object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="creationDate">Initial value of CreationDate.</param>
        /// <param name="status">Initial value of Status.</param>
        public static PhotoAlbum CreatePhotoAlbum(global::System.Guid id, string name, global::System.DateTime creationDate, int status)
        {
            PhotoAlbum photoAlbum = new PhotoAlbum();
            photoAlbum.Id = id;
            photoAlbum.Name = name;
            photoAlbum.CreationDate = creationDate;
            photoAlbum.Status = status;
            return photoAlbum;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this.ReportPropertyChanging("CreationDate");
                this._CreationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreationDate");
                this.OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_Photo_PhotoAlbum", "Photo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Photo> Photo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Photo>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "Photo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Photo>("PhotoAlbumModel.FK_Photo_PhotoAlbum", "Photo", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PhotoAlbumModel.PhotoComment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PhotoAlbumModel", Name="PhotoComment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PhotoComment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PhotoComment object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="comment">Initial value of Comment.</param>
        /// <param name="dateTime">Initial value of DateTime.</param>
        public static PhotoComment CreatePhotoComment(global::System.Guid id, string comment, global::System.DateTime dateTime)
        {
            PhotoComment photoComment = new PhotoComment();
            photoComment.Id = id;
            photoComment.Comment = comment;
            photoComment.DateTime = dateTime;
            return photoComment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property DateTime in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return this._DateTime;
            }
            set
            {
                this.OnDateTimeChanging(value);
                this.ReportPropertyChanging("DateTime");
                this._DateTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateTime");
                this.OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_PhotoComment_Photo", "Photo")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Photo Photo
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Photo>("PhotoAlbumModel.FK_PhotoComment_Photo", "Photo").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Photo>("PhotoAlbumModel.FK_PhotoComment_Photo", "Photo").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Photo in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Photo> PhotoReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Photo>("PhotoAlbumModel.FK_PhotoComment_Photo", "Photo");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Photo>("PhotoAlbumModel.FK_PhotoComment_Photo", "Photo", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_PhotoComment_Users", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PhotoAlbumModel.FK_PhotoComment_Users", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PhotoAlbumModel.FK_PhotoComment_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("PhotoAlbumModel.FK_PhotoComment_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("PhotoAlbumModel.FK_PhotoComment_Users", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for PhotoAlbumModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PhotoAlbumModel", Name="sysdiagrams")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class sysdiagrams : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this.ReportPropertyChanging("principal_id");
                this._principal_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("principal_id");
                this.Onprincipal_idChanged();
            }
        }
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this.ReportPropertyChanging("diagram_id");
                this._diagram_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("diagram_id");
                this.Ondiagram_idChanged();
            }
        }
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this.ReportPropertyChanging("version");
                this._version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("version");
                this.OnversionChanged();
            }
        }
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._definition);
            }
            set
            {
                this.OndefinitionChanging(value);
                this.ReportPropertyChanging("definition");
                this._definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("definition");
                this.OndefinitionChanged();
            }
        }
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
    }
    /// <summary>
    /// There are no comments for PhotoAlbumModel.Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="PhotoAlbumModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        public static Users CreateUsers(global::System.Guid userId)
        {
            Users users = new Users();
            users.UserId = userId;
            return users;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for PhotoComment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("PhotoAlbumModel", "FK_PhotoComment_Users", "PhotoComment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PhotoComment> PhotoComment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PhotoComment>("PhotoAlbumModel.FK_PhotoComment_Users", "PhotoComment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PhotoComment>("PhotoAlbumModel.FK_PhotoComment_Users", "PhotoComment", value);
                }
            }
        }
    }
}
